apiVersion: v1
name: rancher-vsphere-csi
version: 2.3.0
appVersion: 2.3.1
kubeVersion: 1.19 - 1.21
description: vSphere Cloud Storage Interface (CSI)
sources:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver
icon: https://charts.rancher.io/assets/logos/vsphere-csi.svg
maintainers:
  - name: Rancher
    email: caleb@rancher.com
keywords:
  - infrastructure
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/release-name: vsphere-csi
  catalog.cattle.io/display-name: "vSphere CSI"
  catalog.cattle.io/os: linux
  catalog.cattle.io/rancher-version: ">= 2.5.0-0 <= 2.5.99-0"
